dist: trusty
language: node_js
node_js:
- '8'
cache: yarn
jobs:
  include:
  - stage: test
    script:
      - npm test
  - stage: deploy
    script:
      - '[ "$TRAVIS_BRANCH" != "master" ] && travis_terminate 0 || :'