dist: trusty
language: node_js
node_js:
- '8'
cache: yarn
addons:
  ssh_known_hosts: moukari.assembly.org
before_install:
- openssl aes-256-cbc -K $encrypted_a4f06b6584ec_key -iv $encrypted_a4f06b6584ec_iv
  -in secrets.tar.gz.enc -out secrets.tar.gz -d
- tar zxvf secrets.tar.gz
- mv deploy/ssh_config ~/.ssh/config
- mv deploy/deployment_key ~/.ssh/id_rsa
- chmod 0600 ~/.ssh/*
jobs:
  include:
  - stage: test
    script:
    - npm test
  - stage: deploy
    script:
    - '[ "$TRAVIS_BRANCH" != "master" ] && travis_terminate 0 || :'
    - './deploy.sh'
